### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property 'click' of null

### ISSUE THREAD

**Issue by mithro** [gr2m/glitch-deploy#9]
```
$ npx glitch-deploy
Downloading Chromium r515411 - 95.4 Mb [====================] 100% 0.0s 
Error: Evaluation failed: TypeError: Cannot read property 'click' of null
    at <anonymous>:2:81
    at ExecutionContext.evaluateHandle (/home/tansell/.npm/_npx/201248/lib/node_modules/glitch-deploy/node_modules/puppeteer/lib/ExecutionContext.js:66:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by gr2m** [comment]
Thanks for reporting the issue @mithro. Unfortunately I won’t be able to look into it right now, but happy to help out if you submit a pull request investigating the problem 🙌

**Comment by mithro** [comment]
@gr2m I'm afraid I'm not sure where to begin with this (not using node normally) - I think the issue is when trying to install puppeteer?

**Comment by gr2m** [comment]
I think the install worked fine. The error `Cannot read property 'click' of null` sounds more like Glitch changed something in the UI and a link or button that existed before is no longer there, or the CSS selector changed

**Comment by zieka** [comment]
just ran into this looks like glitch now has a login button that needs to be clicked first to expose the github login UI element
